services:
  app:
    container_name: calcprob-trading-prod-app
    image: ale90qm/calcprob-trading:latest
    restart: always
    # NO HAY VOLÚMENES AQUÍ. El código vive y muere dentro de la imagen.

  nginx:
    container_name: calcprob-trading-prod-nginx
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      # Nginx solo necesita SU PROPIO archivo de configuración. Nada más.
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

# YA NO NECESITAMOS LA SECCIÓN 'volumes:' AL FINAL.